package com.cmsproject.database;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;

public class DatabaseInitializer {

    public static void initialize() {
        String createUserTable = "CREATE TABLE IF NOT EXISTS Users (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "username VARCHAR(50) UNIQUE NOT NULL," +
                "password VARCHAR(255) NOT NULL," +
                "is_admin BOOLEAN DEFAULT FALSE" +
                ");";

        String createContentTable = "CREATE TABLE IF NOT EXISTS Contents (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "title VARCHAR(100) NOT NULL," +
                "body VARCHAR(5000) NOT NULL," +
                "author VARCHAR(50) NOT NULL" +
                ");";

        Connection connection = null;
        Statement statement = null;

        try {
            connection = DatabaseManager.getConnection();
            statement = connection.createStatement();
            statement.execute(createUserTable);
            statement.execute(createContentTable);
            System.out.println("Tabelas criadas com sucesso!");
        } catch (SQLException e) {
            System.out.println("Erro ao criar tabelas: " + e.getMessage());
        } finally {
            try {
                if (statement != null) statement.close();
                if (connection != null) connection.close();
            } catch (SQLException e) {
                System.out.println("Erro ao fechar recursos: " + e.getMessage());
            }
        }
    }
}