package com.cmsproject.database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseManager {
    private static final String URL = "jdbc:hsqldb:file:mydatabase/mydb;shutdown=false";
    private static final String USER = "SA";
    private static final String PASSWORD = "";

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }

    public static void initializeDatabase() {
        String createUserTable = "CREATE TABLE IF NOT EXISTS Users (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "username VARCHAR(50) UNIQUE NOT NULL," +
                "password VARCHAR(255) NOT NULL," +
                "is_admin BOOLEAN DEFAULT FALSE" +
                ");";

        String createContentTable = "CREATE TABLE IF NOT EXISTS Contents (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "title VARCHAR(100) NOT NULL," +
                "body CLOB NOT NULL," +
                "author VARCHAR(50) NOT NULL" +
                ");";

        try (Connection connection = getConnection();
             Statement statement = connection.createStatement()) {

            statement.execute(createUserTable);
            statement.execute(createContentTable);
            System.out.println("Tabelas criadas com sucesso!");
        } catch (SQLException e) {
            System.out.println("Erro ao inicializar o banco de dados: " + e.getMessage());
        }
    }
}
